COMMENT ON TABLE gtsu_search IS 'Ежедневный Доклад ГЦУ ОАО РЖД — плоская иерархическая витрина показателей.';
COMMENT ON COLUMN gtsu_search.report_date IS 'Дата доклада ГЦУ.';
COMMENT ON COLUMN gtsu_search.section_code IS 'Код раздела доклада (I, II, III...).';
COMMENT ON COLUMN gtsu_search.section_title IS 'Название раздела доклада.';
COMMENT ON COLUMN gtsu_search.sheet_name IS 'Имя листа исходного Excel.';
COMMENT ON COLUMN gtsu_search.item_number IS 'Иерархический номер показателя (напр. 1, 1.1, 1.1.7).';
COMMENT ON COLUMN gtsu_search.item_depth IS 'Глубина в дереве показателей (1=раздел, 3=лист).';
COMMENT ON COLUMN gtsu_search.parent_path IS 'Путь по родительским разделам дерева (через '' > ''). Здесь лежит ТЕМА/категория показателя.';
COMMENT ON COLUMN gtsu_search.indicator IS 'Название ИМЕННО этой строки — лист дерева. У детализированных строк это конкретный объект (напр. название железной дороги), а НЕ тема.';
COMMENT ON COLUMN gtsu_search.full_indicator IS 'parent_path + '' > '' + indicator. Используйте для поиска по теме (ILIKE), т.к. объединяет категорию и лист.';
COMMENT ON COLUMN gtsu_search.unit IS 'Единица измерения.';
COMMENT ON COLUMN gtsu_search.responsible IS 'Ответственное подразделение (ЦД, ЦТ, ЦФТО...).';
COMMENT ON COLUMN gtsu_search.color_marker IS 'Зона: 2=красная, 1=жёлтая, 0=зелёная, NULL=без зоны.';
COMMENT ON COLUMN gtsu_search.metrics IS 'JSONB с числами. Отклонения «к плану»/«к 2021» — доли: -0.0979 = -9.79%.';
COMMENT ON COLUMN gtsu_search.text_comment IS 'Текстовый комментарий из доклада.';
COMMENT ON COLUMN gtsu_search.management_actions IS 'Предлагаемые управленческие решения.';
COMMENT ON COLUMN gtsu_search.narrative IS 'Человекочитаемый абзац (для полнотекстового поиска).';
COMMENT ON COLUMN gtsu_search.source_row IS 'Номер строки в исходном Excel.';
